### ISSUE TITLE
About the data preprocessing?

### ISSUE THREAD

**Issue by yangrongkun** [565353780/auto-scan2cad#4]
Dear authors, I am interested in this wonderful work, and I'd like to train and test the code. 
However, I meet some troubles in the data processing, could you share more detail about the training and testing about this?
1) the data processing about the data path list in the code, the "scannet_bbox_dataset_folder_path, scannet_object_dataset_folder_path, scan2cad_object_model_map_dataset_folder_path, shapenet_udf_dataset_folder_path" is how to be processed and means what?
![image](https://github.com/user-attachments/assets/1b4b3a63-92b8-435c-84d4-f1cf5a9ffb47)

2) The testing weight could be shared?
Thank you very much.

**Comment by 565353780** [comment]
Hello, I apologize for the delay. The data initialization script has always been included in the code repository, but it might not be easily noticeable. I have now reorganized the script and provided some explanations in the README. Feel free to give it a try!

And the testing weight will also be released soon~ Thank you for your attention!
